step-01:
  title: "Исходное дерево rootfs"
  task: _task.qmd
  theory: _theory.qmd
  actions:
      pre-step:
        exec:
          - prepare.sh
      check:
        exec:
          - check/check.sh
      solution:
        exec:
          - solution/solve.sh
