step-05:
  title: "tmpfs для runtime state"
  task: _task.qmd
  theory: _theory.qmd
  actions:
      check:
        exec:
          - check/check.sh
      solution:
        exec:
          - solution/solve.sh
