capstone-swarm-10:
  title: "10. Failure recovery"
  theory: _theory.qmd
  task: _task.qmd
  actions:
      check:
        exec:
          - check.sh
      solution:
        exec:
          - solution.sh
