cgroups-v2-09:
  title: "Freezer как мягкая гибернация без сохранения памяти"
  task: _task.qmd
  theory: _theory.qmd
  actions:
      pre-step:
        exec:
          - pre-step.bash
      check:
        exec:
          - check.bash
      solution:
        exec:
          - solution.bash
      post-step:
        exec:
          - post-step.bash
