task-rescheduling:
  title: "05. Task rescheduling"
  task: _task.qmd
  theory: _theory.qmd
  actions:
    pre-step:
      exec:
        - pre-step.sh
    check:
      exec:
        - check.sh
    solution:
      exec:
        - solution.sh
