format:
  pdf:
    code-block-bg: "#FCFCFC"
    latex-auto-install: false
    use-rsvg-convert: true
    documentclass: scrbook
    classoption: [twoside=false]
    toc-depth: 1
    number-sections: true
    number-depth: 2
    papersize: a4
    colorlinks: true
    mainfont: Times New Roman
    sansfont: Times New Roman
    monofont: Noto Sans Mono Black
    include-in-header:
      - text: |
         \usepackage{fontspec}
         \usepackage{fontawesome5}
