project:
  type: book
  output-dir: _s-book

book:
  chapters:
    - index.qmd
    - linux/filesystem/permission.qmd
    - linux/package.qmd

    - part: "Задания"
      chapters:
        - lab/ubuntu/main.qmd
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        - lab/libvirt/main.qmd
||||||| f589c88
=======
        - lab/docker/compose-debugging/main.qmd
>>>>>>> remotes/origin/codex/create-debugging-lab-for-compose-applications
||||||| 6df1dcb
=======
        - lab/docker/compose/main.qmd
>>>>>>> remotes/origin/codex/create-docker-compose-lab-for-multi-container-app
||||||| 6df1dcb
=======
        - lab/docker/images/main.qmd
>>>>>>> remotes/origin/codex/create-docker-lab-for-reproducible-builds
||||||| 6df1dcb
=======
        - lab/docker/storage/main.qmd
>>>>>>> remotes/origin/codex/create-docker-lab-on-volumes-and-mounts
||||||| 6df1dcb
=======
        - lab/docker/networking/main.qmd
>>>>>>> remotes/origin/codex/create-docker-networking-lab
||||||| 6df1dcb
=======
        - lab/docker/swarm-basic/main.qmd
>>>>>>> remotes/origin/codex/create-docker-swarm-lab-structure
||||||| 6df1dcb
=======
        - lab/docker/capstone-compose/main.qmd
>>>>>>> remotes/origin/codex/create-docker/compose-capstone-lab-assignment
||||||| 6df1dcb
=======
        - lab/docker/lowlevel-checkpoint-restore/main.qmd
>>>>>>> remotes/origin/codex/create-lab-on-checkpoint/restore-in-docker

  appendices:
    - part: "Командные оболочки"
      chapters:
        - shell/sh.qmd
        - shell/bash.qmd
    - part: "Инструменты"
      chapters:
        - tools/nano/main.qmd
        - tools/curl.qmd
    - part: tools/user/overview.qmd
      chapters:
        - tools/user/adduser.qmd
        - tools/user/addgroup.qmd
        - tools/user/usermod.qmd

