project:
  type: book
  output-dir: _s-book

book:
  chapters:
    - index.qmd
    - linux/filesystem/permission.qmd
    - linux/package.qmd

    - part: "Задания"
      chapters:
        - lab/ubuntu/main.qmd
        - lab/libvirt/main.qmd

  appendices:
    - part: "Командные оболочки"
      chapters:
        - shell/sh.qmd
        - shell/bash.qmd
    - part: "Инструменты"
      chapters:
        - tools/nano/main.qmd
        - tools/curl.qmd
    - part: tools/user/overview.qmd
      chapters:
        - tools/user/adduser.qmd
        - tools/user/addgroup.qmd
        - tools/user/usermod.qmd

