08-user:
  title: "08. User namespace и отображение UID/GID"
  theory: _theory.qmd
  task: _task.qmd
  actions:
        pre-step: 
          exec:
            - pre-step.bash
        check:
          exec:
            - check.bash
        solution:
          exec:
            - solution.bash
