04-userns-remap:
  title: "User namespace remap"
  task: _task.qmd
  theory: _theory.qmd
  actions:
    pre-step:
      exec:
        - /workspace/VirtualizationAndCloud/lab/docker/lowlevel-security-primitives/assets/prepare.sh
    check:
      exec:
        - check/check.sh
    solution:
      exec:
        - solution/solution.sh
