03-pid:
  title: "03. PID namespace и роль процесса 1"
  theory: _theory.qmd
  task: _task.qmd
  actions:
        pre-step:
          exec:
            - pre-step.bash
        check:
          exec:
            - check.bash
        solution:
          exec: 
            - solution.bash
