config:
  title: "06. Отделение конфигурации"
  task: _task.qmd
  theory: _theory.qmd
  actions:
    check:
      exec:
        - check/check.sh
    solution:
      import:
        - solution/solution.sh
      exec:
        - solution/solution.sh
