isolation:
  title: "Isolation"
  task: _task.qmd
  theory: _theory.qmd
  actions:
    pre-step:
      exec:
        - ../prepare
    check:
      exec:
        - check
    solution:
      exec:
        - solution
