cgroups-v2-10:
  title: "Связь Docker resource limits с cgroups"
  task: _task.qmd
  theory: _theory.qmd
  actions:
      pre-step:
        exec:
          - pre-step.bash
      check:
        exec:
          - check.bash
      solution:
        exec:
          - solution.bash
      post-step:
        exec:
          - post-step.bash
