06-lifecycle:
  title: "Stop, start и restart"
  task: _task.qmd
  theory: _theory.qmd
  actions:
      check:
        exec:
          - check.sh
      solution:
        exec:
          - solution.sh
