cgroups-v2-04:
  title: "CPU quota через cpu.max"
  task: _task.qmd
  theory: _theory.qmd
  actions:
      pre-step:
        exec:
          - pre-step.bash
      check:
        exec:
          - check.bash
      solution:
        exec:
          - solution.bash
