01-inventory:
  title: "Инвентаризация Docker Engine"
  task: _task.qmd
  theory: _theory.qmd
  actions:
      pre-step:
        exec:
          - pre-step.sh
      check:
        exec:
          - check.sh
      solution:
        exec:
          - solution.sh
