02-first-service:
  title: "Запуск первого сервиса"
  task: _task.qmd
  theory: _theory.qmd
  actions:
      check:
        exec:
          - check.sh
      solution:
        exec:
          - solution.sh
