07-network:
  title: "07. Network namespace без Docker"
  theory: _theory.qmd
  task: _task.qmd
  actions:
        pre-step: 
          exec:
            - pre-step.bash
        check:
          exec:
            - check.bash
        solution:
          exec:
            - solution.bash
