step-11:
  title: "Очистка checkpoint artifacts"
  task: _task.qmd
  theory: _theory.qmd
  actions:
      check:
        exec:
          - check/check.sh
      solution:
        exec:
          - solution/solution.sh
