netlab-10:
  title: "Очистка сетевых объектов"
  theory: _theory.qmd
  task: _task.qmd
  actions:
    pre-step:
      exec:
        - prepare
        - pre-step
    check:
      exec:
        - check
    solution:
      exec:
        - solution
    post-step:
      exec:
        - post-step
