swarm-init:
  title: "01. Swarm init"
  task: _task.qmd
  theory: _theory.qmd
  actions:
    pre-step:
      exec:
        - prepare.sh
    check:
      exec:
        - check.sh
    solution:
      exec:
        - solution.sh
