step-02:
  title: "Проверка поддержки CRIU и Docker checkpoint"
  task: _task.qmd
  theory: _theory.qmd
  actions:
      check:
        exec:
          - check/check.sh
      solution:
        exec:
          - solution/solution.sh
