isolation:
  title: "Сетевая изоляция"
  task: _task.qmd
  theory: _theory.qmd
  actions:
    pre-step:
      exec:
        - prepare
        - pre-step
    check:
      exec:
        - check
    solution:
      exec:
        - solution
    post-step:
      exec:
        - post-step
