backup-files:
  title: "Согласование с файловым backup"
  task: _task.qmd
  theory: _theory.qmd
  actions:
      check:
        exec:
          - check.sh
      solution:
        exec:
          - solution.sh
