02-uts:
  title: "02. UTS namespace и hostname процесса"
  theory: _theory.qmd
  task: _task.qmd
  actions:
        pre-step:
          exec:
           - pre-step.bash
        check:
          exec:
            - check.bash
        solution:
          exec:
            - solution.bash
